### ISSUE TITLE
Drive down top errors impacting Graph Explorer

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#1070]
@Onokaev  & @MaggieKimani1 this is worth investigating, for some reason, we have permissions calls failing
![image](https://user-images.githubusercontent.com/9458079/136073084-0b08a3c9-71ed-4469-86a7-4b3a6943eda8.png)

- [x] #1179
- [x] Failing authentication errors
- [x] #1180
- [x] #1181

**_Top errors and affected users_**
![image](https://user-images.githubusercontent.com/9458079/136074130-0e4c540e-337a-487f-87d5-09355da8e5bd.png)

The images are a bit 'foggy', the BI-dashboard could not load properly 
**_Monaco editor display errors_**
![image](https://user-images.githubusercontent.com/9458079/136074232-e80d7575-fddf-42a9-85eb-463b8c103f6f.png)

**_Documentation link errors_**
![image](https://user-images.githubusercontent.com/9458079/136074388-22b3a6dd-0211-4df7-a446-6bf1276d074b.png)

[AB#10826](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10826)

**Comment by MaggieKimani1** [comment]
@ddyett Let me counter check with DevX API telemetry data and see why we're recording so many failures for the `/Permissions` endpoint.

**Comment by Onokaev** [comment]
@ddyett We are looking into it

**Comment by Onokaev** [comment]
Errors from the monaco editor were as a result of failures in JSON parsing. However, when parsing fails, the content that was being parsed is displayed as is and does not break the application. We will continue to have these errors.

The failures in links is due to CORS errors. We expect all external links to throw these kinds of errors. The links will still open their respective pages, but we will still record the errors that are thrown by the app. 

Authentication errors were resolved in this PR: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1060
We have not had any consistent authentication issues since this change.

Failing permissions calls were resolved on the devx-api side. Permissions calls have been reliable for quite some time
