### ISSUE TITLE
Get groups with /me/memberOf

### ISSUE THREAD

**Issue by ar1eger** [microsoftgraph/microsoft-graph-explorer-v4#1134]
**Describe the bug**
logged into my personal account
Select from examples "Get All groups I belong to" from Samples queries returns URL not found
 
Response: Not Found - 404 - 495ms
   
1. Log into my Azure account
2. From Samples queries: Choose "Get All groups I belong to"
3. Select "Run Query"  (the URL is: https://graph.microsoft.com/v1.0/me/memberOf)
Response: Not Found - 404 - 495ms
{
    "error": {
        "code": "",
        "message": "No HTTP resource was found that matches the request URI 'https://outlook.office365.com:444/profile/v1.0/users('CID:xxxxxxxxxxx')/profile/memberOf?api-version=AGSV1-internal'.",
        "innerError": {
            "date": "2021-09-24T00:09:10",
            "request-id": "1ca41a30-c9cd-4c3d-a835-13aa402d0168",
            "client-request-id": "e907b7af-df93-a280-a94c-610ab4c7422d"
        }

**Expected behavior**
Returns Azure directory groups that user is a member of

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 93.0.961.52 (Official build) (64-bit)

**Additional context**

**Comment by ElinorW** [comment]
Hey @ar1eger, 
This error is returned because this query is not supported on **personal accounts** (e.g. an outlook account). It is only supported on **Delegated (work and school accounts)** . 

Please refer to this [documentation](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http) for more details. 

_Screenshot of supported accounts and Permissions required._
![image](https://user-images.githubusercontent.com/18407044/135076497-e4f1f151-e6e4-4b54-b52f-66bcb6d63659.png)
