### ISSUE TITLE
Monaco editor display return 'OPERATIONAL ERROR' errors and some issue around JSON parsing

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#1181]

**Comment by Onokaev** [comment]
The JSON.parse function throws an error whenever a json string passed to has invalid characters e.g coma at the end:
JSON.parse({ x: 5,  }). For this example, the parse function throws an error because of the trailing coma. The subsequent JSON.stringify function however correctly converts the example to a valid JSON string which is displayed on the Monaco editor.

The thrown error is logged as an OPERATIONAL ERROR. This error is expected as explained above.
The error does not block the subsequent conversion of the json objects with trailing comas to valid json strings
