### ISSUE TITLE
Not showing updated display picture after querying for " my photo ".

### ISSUE THREAD

**Issue by Konohamaru04** [microsoftgraph/microsoft-graph-explorer-v4#1269]
Not showing updated display picture after querying for " my photo ".

1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)  .
2. Login.
3. Click on " **GET** my photo " query.

**Expected behavior**
Should show updated display picture.

**Screenshots**
![image](https://user-images.githubusercontent.com/41485055/143537131-865eaa19-ff2e-4906-83e5-8a9fcc2eaffa.png)

 - OS: Windows 10 Professional
 - Browser : Chrome

**Comment by RabebOthmani** [comment]
Hi @Konohamaru04 , I've tested and I can confirm that the image was not updated immediately, there was a bit of delay. This isn't an issue with Graph Explorer though, it is due to the different sources the picture can be from/to. 
I'd recommend posting the issue on https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1273 for the right team to look at it.
