### ISSUE TITLE
[Resource Explorer] Display HTTP methods in Resource explorer like they are shown in Samples Queries.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1322]
![image](https://user-images.githubusercontent.com/447694/146782422-4d693bf4-4cd2-420b-a938-6025098e088b.png)

This will allow "selecting" a resource by just clicking on the method.  No need to use context menu.
Also the context menu should allow "add to collection" for specific HTTP methods.

**Comment by RabebOthmani** [comment]
As a user, when I'm on Resources Explorer 
I want to see methods part of the resources tree similar to Sample Queries 
So that I have a consistent experience across features

**Acceptance Criteria**

- Display HTTP methods part of the resources tree.
- Clicking on a method would automatically select it and set it in the 'run query' area
- Remove 'Set query' from context menu
