### ISSUE TITLE
Question about Multi-Tenant Auth

### ISSUE THREAD

**Issue by kachihro** [microsoftgraph/microsoft-graph-explorer-v4#1362]
Hello,

Not an issue with Graph Explorer - but wondering HOW the project (final website) is able to provide the LOGIN and it will ask permission, for the chosen tenant...

I've been able to secure an ASP.NET code project to ONE tenant - but how to allow for multi-tenant ?   This is first steps/PoC for a utility w/ SharePoint - and would request permissions - when signing in.

But - I get a message saying the user is not allowed to access the client id - in the 'source' tenant.    

How does GRAPH EXPLORER do it ??

**Comment by ElinorW** [comment]
Hey @kachihro,

Graph Explorer is able to have multi-tenant auth is because it is registered on Azure App Registrations and its settings enable multiple account types

Is your application registered on Azure? When registering the application, there's a section that allows you to select the kind of accounts you'd want to support. 
![image](https://user-images.githubusercontent.com/18407044/150789172-90e0de86-0062-491c-8b81-c11a93fb57e8.png)

Let me know if this helps...
