### ISSUE TITLE
[Resource Explorer] Resizing the sidebar below a minimum makes everything disappear

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1534]
when resizing the sidebar to make it smaller, at some point everything on the sidebar disappear and the initial selection is gone, meaning: if I'm selecting the Resource Explorer tab then I resize to a minimum, everything would disappear. Then if I resize again to make my sidebar bigger, I start seeing my items but it is the sample queries tab that is selected not the Resource Explorer tab. 

<img src="https://user-images.githubusercontent.com/5781590/157024123-90c5e2b1-9ffa-4c38-b208-c8fc7066a912.png" height="400" />

**Comment by thewahome** [comment]
@RabebOthmani this satisfied a previous request to reduce the content on the screen. Notice that the sample queries / history also are not featured in this minimised view. 

We can repurpose this to be a new feature request so that we describe how best to handle things after the minimising of the sidebar

**Comment by RabebOthmani** [comment]
As discussed @thewahome , happy to leave this for future work

**Comment by ddyett** [comment]
placing for PM reviews as it requires definition of the expected behavior per comments above.

**Comment by RabebOthmani** [comment]
With the new header in place and modifications made to the sidebar, this issue is no longer valid. I'm closing it.
