### ISSUE TITLE
"PATCH /users/{id}" does not return "Directory.AccessAsUser.All" permission in the "Modify permissions" tab

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-explorer-v4#2177]
**Describe the bug**
"PATCH /users/{id}" requires the Directory.AccessAsUser.All permission to be consented to update a user's password. However, the "Modify permissions" tab does not return this permission.

**To Reproduce**
1. Go to Graph Explorer
2. Login with an AAD account.
3. Write the "https://graph.microsoft.com/v1.0/users/{id}" endpoint and set the method as PATCH.
4. Go to the "Modify permissions" tab. It does not show the "Directory.AccessAsUser.All" permission to be consented.

**Expected behavior**
I expected the "Directory.AccessAsUser.All" permission to appear in the "Modify permissions" tab, as it is needed to update a user's password.

**Screenshots**
![image](https://user-images.githubusercontent.com/103036544/196967133-7de3f836-e172-47d8-8da9-9305ddc3ec86.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Version 106.0.1370.42 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
This happens both with v1.0 and beta endpoints.

**Comment by Onokaev** [comment]
Hey @manuel-falcao-magalhaes. Apologies for this. We don't have a full 1:1 mapping of endpoint to permissions required. This is currently work in progress.
A quick workaround to this issue is to open the permissions panel and give consent to the Directory.AccessAsUser.All permission from there:
Steps:
1. Click on your profile
![image](https://user-images.githubusercontent.com/45680252/197126638-e08e4945-c263-4619-ba8a-8279fd932e82.png)
2. Click on 'Consent to permissions' then search for the permissions on the panel displayed
![image](https://user-images.githubusercontent.com/45680252/197126791-e9a5f978-c399-4dca-9828-a8156a424b8e.png)
3. Click Consent once you've selected the permission

Let me know if you need any further assistance

**Comment by manuel-falcao-magalhaes** [comment]
> Hey @manuel-falcao-magalhaes. Apologies for this. We don't have a full 1:1 mapping of endpoint to permissions required. This is currently work in progress. A quick workaround to this issue is to open the permissions panel and give consent to the Directory.AccessAsUser.All permission from there: Steps:
> 
> 1. Click on your profile
>    ![image](https://user-images.githubusercontent.com/45680252/197126638-e08e4945-c263-4619-ba8a-8279fd932e82.png)
> 2. Click on 'Consent to permissions' then search for the permissions on the panel displayed
>    ![image](https://user-images.githubusercontent.com/45680252/197126791-e9a5f978-c399-4dca-9828-a8156a424b8e.png)
> 3. Click Consent once you've selected the permission
> 
> Let me know if you need any further assistance

Hi @Onokaev, thank you for the workaround, I successfully used this approach. I'm also glad to know that full 1:1 mapping of endpoint to permissions required is being worked on. No further assistance needed, thanks.
