### ISSUE TITLE
Need show more meta data form App Service Resource in  Azure Resource Graph Explorer Page 

### ISSUE THREAD

**Issue by LuBu0505** [microsoftgraph/microsoft-graph-explorer-v4#2212]
**Is your feature request related to a problem? Please describe.**
we would like to check the App Service meta data (like TLS version, Health Check, Stack infor and so on) in the Aure Resource Graph Explorer page.  But currently, Those properties always return null. 
![image](https://user-images.githubusercontent.com/69841770/199921158-bedabc1c-0051-45e2-b3a6-a90941eadf33.png)

**Describe the solution you'd like**
Please show the correct value which map the real data from App Service side

**Describe alternatives you've considered**

**Additional context**
The App Service REST API can get this value, just the Graph Explorer didn't sync and mapping it. 

REST API: https://learn.microsoft.com/zh-cn/rest/api/appservice/web-apps/get-configuration

**Comment by RabebOthmani** [comment]
Hi @LuBu0505 This repo is for Graph Explorer while the product you are referring to is the Azure Resource Explorer, which is not something we work on. I apologize for the confusion caused by the similarity of names and advice to report the issue on [the Microsoft Community forum ](https://answers.microsoft.com/) or with the Azure team.
