### ISSUE TITLE
Asked for admin approval when permission says it's not required

### ISSUE THREAD

**Issue by heaths** [microsoftgraph/microsoft-graph-explorer-v4#2754]
**Describe the bug**
The list of permissions says that admin approval is not required, yet I'm being asked for admin approval/

**To Reproduce**
1. Sign into Microsoft Graph Explorer.
2. GET https://graph.microsoft.com/v1.0/chats
3. Click Modify Permissions in request
4. See list. Notice none say admin approval required. Click Consent.

**Expected behavior**
I can grant permissions to Graph Explorer as needed, at least for those permissions that say admin approval isn't necessary.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/1532486/7ebf6f41-bb9c-49d8-b29e-ada853e6a4ef)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge Dev
 - Version: 117.0.2045.7 (Official build) dev (64-bit)

**Comment by Onokaev** [comment]
Hey @heaths. A permission may not require admin consent, but there could be tenant restrictions that still prevent you from consenting to these permissions. 
I recommend seeking admin approval for this case.
If you are trying to test an endpoint, I recommend using a sandbox tenant which you have control over: https://developer.microsoft.com/en-US/microsoft-365/dev-program

Let me know if this helps

**Comment by heaths** [comment]
My bug report was less about needing admin permission, and more about the confusing messaging. One view says no *"admin* consent required" (emphasis mine) while another says "need *admin* approval". Which is it? Assuming I'm a customer that doesn't know whether the permission required admin approval or some tenant admin required it, perhaps wording could be fixed. If the dialog is because of tenant restrictions, perhaps "Need tenant admin approval"? How am I supposed to know who to contact? You just keep using the word "admin" everywhere and it's a bit confusing.

**Comment by ElinorW** [comment]
> My bug report was less about needing admin permission, and more about the confusing messaging. One view says no _"admin_ consent required" (emphasis mine) while another says "need _admin_ approval". Which is it? Assuming I'm a customer that doesn't know whether the permission required admin approval, or some tenant admin required it, perhaps wording could be fixed. If the dialog is because of tenant restrictions, perhaps "Need tenant admin approval"? How am I supposed to know who to contact? You just keep using the word "admin" everywhere and it's a bit confusing.

Hi @heaths, 
Thanks for bringing this to our attention. I understand how the messaging around "admin consent can be confusing.  
 
To clarify, Graph Explorer is primarily intended for testing and experimentation, not for use with production data. The "Admin consent required" column is there to indicate what permissions would typically need admin consent in a testing environment helping users anticipate the kind of approvals that might be needed in a real-world scenario. 

However, I completely understand that when you see mixed messaging, it can be unclear whether admin approval is needed due to the specific tenant's policies or more general admin consent. Your suggestion to differentiate between "admin" and "tenant admin" approval is valuable and I'll be sure to pass it along to the team. In the meantime, if you're ever unsure it's best to contact your tenant admin for clarity.

**Comment by heaths** [comment]
How are we supposed to know who the tenant admins are? As a fellow Microsoftie, you no doubt deal with numerous tenants all day.
