### ISSUE TITLE
https://graph.microsoft.com/beta/devices/{device-id} should indicate https://graph.microsoft.com/beta/devices/{object-ID}

### ISSUE THREAD

**Issue by LuisAmadeo** [microsoftgraph/microsoft-graph-explorer-v4#3005]
**Describe the bug**
In graph explorer when you try to get the info from a device in AAD the info provided by the portal suggest to enter a deviceID to get the info but the portal expects an objectid instead and will not work with a deviceID

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'https://graph.microsoft.com/beta/devices/{device-id}'
The device resource ask for a deviceID to get the info from a device but it only work if you supply an objectID and did not work with deviceid
**Expected behavior**
I expect thet if the portal ask for a deviceID it will work with a DeviceID. It it needs an ObjectID it should say  'https://graph.microsoft.com/beta/devices/{object-id}'

**Desktop (please complete the following information):**
 - OS: Windows 11 22h3 but should happens with any OS
 - Browser Microsoft Edge
 - Version 122.0.2365.16

**Additional context**

**Comment by thewahome** [comment]
Hello @LuisAmadeo, 
I see what you mean, the documentation should instead say {object-id} and not {device-id} since it's the former that works.

We use the OpenAPI description to give the suggestions for the next part of the document. In the documentation [here](https://learn.microsoft.com/en-gb/graph/api/device-get?view=graph-rest-1.0) and the OpenAPI description [here after you search for `/devices/`](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml) the place holder value has been defined as {device-id}

Since we are not the right repository for this and merely consumers of what has been defined. I'd suggest you [open an issue in the metadata repository](https://github.com/microsoftgraph/msgraph-metadata/issues)

**Comment by ElinorW** [comment]
/
