### ISSUE TITLE
MS Graph Explorer returning 400 instead 200 for passwordlessMicrosoftAuthenticator

### ISSUE THREAD

**Issue by mifarca** [microsoftgraph/microsoft-graph-explorer-v4#773]
**Describe the bug**

Using the MS Graph GET request: https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/passwordlessMicrosoftAuthenticator  is giving a 400 error on Graph Explorer with no info or request IDs.
While running Fiddler at the same time, we see that we get a 200 OK in the trace.

**To Reproduce**
1. Go to 'Graph Explorer'
2. Click on 'Run Query'
3. Scroll down to 'The Response Preview'
4. See error: Error 400. With no Body or information.

**Expected behavior**
The expected behavior is for this API request to Work or if not, provide the error description.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]: Edge, Chrome
 - Version [e.g. 22]: Latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: N/A

**Additional context**
 
[AB#7475](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7475)

**Comment by ElinorW** [comment]
@mifarca The 400-Bad Request Error was returned because the request seems to be deprecated. This is indicated in the docs [here](https://docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta)

A possible solution could be running this method instead
`https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/microsoftAuthenticator`
Find the link to the documentation [here]( https://docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta)

**Comment by ElinorW** [comment]
Closing this issue.
