### ISSUE TITLE
Can't signin with MFA

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/microsoft-graph-explorer-v4#973]
**Describe the bug**
My tenet requires MFA and I use MS authenticator on my phone

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Sign in to Graph Explorer'  
3. Enter user name , password ang the MFA 
4. no error but my ID not showing. I am still ""displayName": "Megan Bowen","

**Expected behavior**
My graph call should be for my tenant

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [latest]

 
[AB#9660](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9660)

**Comment by Onokaev** [comment]
Hi @Ofer-Gal. Are you still experiencing this issue?

**Comment by Ofer-Gal** [comment]
Yes!
a Logon shows, I choose my production ID but never get the authenticator to ask for approval
Graph-Explorer shows error: "Authentication failed - interaction required"
Is there a new version I can test?

**Comment by Onokaev** [comment]
Okay @Ofer-Gal . Please attach screenshots of the steps you are taking to sign in up to the error message.

**Comment by Ofer-Gal** [comment]
Logon
![image](https://user-images.githubusercontent.com/5054931/126386076-083b076d-05bd-4d7a-8fdd-037e1f17ff37.png)
Then
![image](https://user-images.githubusercontent.com/5054931/126386174-c0cad507-488d-44a9-8e0b-1142d8860605.png)

It does not even ask for password.

**Comment by Onokaev** [comment]
Does the issue persist when you try signing in with a different account or a different browser? 
You can try that just to confirm that the issue is not with your account.

**Comment by Ofer-Gal** [comment]
Different browsers / Computers etc..
I got all the way to the authenticator but Graph explorer still not connected

**Comment by Onokaev** [comment]
This appears to be an issue with your tenant. Re-registering MFA should solve this.

If you are the admin, log in to your tenant on https://aad.portal.azure.com/.
![image](https://user-images.githubusercontent.com/45680252/127967158-1f1d3c4d-5064-4d7e-9e3d-1ce371e5b33d.png)

Then click on Users. That should load all users including your admin user profile. Click on the user profile with the MFA issue. 
![image](https://user-images.githubusercontent.com/45680252/127967979-4d533824-4d36-4383-81e6-5bf350f32f0e.png)

Then click on authentication methods
![image](https://user-images.githubusercontent.com/45680252/127968093-e41b788d-8606-44eb-9ec9-6db84c1a5bb4.png)

Here, you can revoke the MFA sessions and try to sign in to Graph Explorer to confirm that you can still sign in, then you can click on 'Require re-register MFA'. Then go back to Graph Explorer and try to sign in again. Follow the prompts which will help you re-register MFA.

**Comment by Onokaev** [comment]
If the admin user is the one with the MFA issue, try revoking all sessions then sign in to GE again. If this doesn't resolve the issue, create a new support request on 'Troubleshooting + Support' on your aad portal.

**Comment by Ofer-Gal** [comment]
My admin is asking what "revoking all sessions" means? where do You do it?
Thanks

**Comment by Onokaev** [comment]
After signing in to https://aad.portal.azure.com/, your admin should click on Users on the left tab : 
![image](https://user-images.githubusercontent.com/45680252/128186809-cb6b891f-5d70-4db6-b954-170b376fcfca.png)

Then click on your user profile that is experiencing the MFA issue: In my case, I clicked on 'Evans Test User'
![image](https://user-images.githubusercontent.com/45680252/128187160-8914faec-8a8d-4b5e-8487-5426065ac301.png)

Then click on 'authentication methods':
![image](https://user-images.githubusercontent.com/45680252/128188583-bbb68871-aec5-4c7b-9335-54cb47f587bf.png)

At the top of the tab, you can see 'Require re-register MFA' and 'Revoke MFA sessions'. 
Revoking MFA sessions will sign you out of all your accounts and you'll have to sign in afresh. 'Require Re-register MFA' makes it so that when you signs in next time, you'll be requested to set up a new MFA authentication method. Either of those should solve the issue

**Comment by Ofer-Gal** [comment]
Thank you
