### ISSUE TITLE
Modify permissions tab deletes all permissions when you move to the select permissions option

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#994]
**Describe the bug**

**To Reproduce**
1. Go to Graph Explorer
2. Run /me query
3. Go to Modify permissions tab and see the permissions listed
4. Go to Select permissions option
5. See error - the modify permissions tab now says there are no permissions for the same query.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#9910](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9910)

**Comment by thewahome** [comment]
Hello @bettirosengugi please add context in the Expected behaviour section. 

The current way things appear is by design so that this issue can be solved: [https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/594](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/594)
